### ISSUE TITLE
In Sweden we have good structure of the PM people over time

### ISSUE THREAD

**Issue by salgo60** [Lisa-Baumgaertner/metadata-enrichment#1]
**Question**: Will you support doing NER just on a subset of WD?

E.g. [Swedish PM people](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden)
* [Swedish Corpus](https://github.com/welfare-state-analytics/riksdagen-corpus) - (I am not part of that)

**Comment by Lisa-Baumgaertner** [comment]
Sorry for the late answer, currently such an extension is not planned.
